language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3.5-6.0.0"
  - "pypy3.5-7.0.0"
  - "pypy3.6-7.0.0"
  - "pypy3.6-7.1.1"
install:
  - pip install -r test-requirements.txt
  - pip install -e .
script:
  - nosetests -q --with-coverage --cover-package=pycron
sudo: false
after_success:
  - coveralls
